# Generated by Django 3.1.7 on 2021-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210309_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='embedded',
        ),
        migrations.AddField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, verbose_name='Vídeo da aula'),
        ),
    ]
