# Generated by Django 3.1.7 on 2021-03-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210310_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(help_text='Ordem de liberação da aula.', unique=True, verbose_name='Ordem'),
        ),
    ]
