# Generated by Django 3.1.7 on 2021-03-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210317_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(help_text='Ordem de liberação da aula.', unique=True, verbose_name='Ordem'),
        ),
    ]
