# Generated by Django 3.1.7 on 2021-03-18 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210317_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(help_text='Ordem de liberação da aula.', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem'),
        ),
    ]
