# Generated by Django 3.1.7 on 2021-03-19 20:33

import courses.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210317_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Use uma imagem com as dimensões 400 x 250.', null=True, upload_to='courses/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(help_text='Ordem de liberação da aula, começando do 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='release_date',
            field=models.DateField(blank=True, help_text='Se for a primeira aula lançada (ordem = 1) esta será a data de início do curso também.', null=True, verbose_name='Data de liberação'),
        ),
        migrations.AlterField(
            model_name='material',
            name='resource',
            field=models.FileField(blank=True, help_text='Recurso usado na aula, como código base, anotações, imagem... Pode ser também o vídeo da aula.', null=True, upload_to=courses.utils.material_directory_path, verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, help_text='URL do vídeo. Por exemplo: https://www.youtube.com/embed/Mp0vhMDI7fA', verbose_name='Vídeo da aula'),
        ),
    ]
